name: project1
channels: 
  - conda-forge
  - defaults
dependencies:
  - ipython=7.12.0
  - nbconvert=5.6.1
  - numpy=1.18.1
  - python=3.8.1
  - opencv=4.2.0
  - scikit-image=0.16.2
  - pandas=1.0.1
  - bokeh=1.4.0
  - selenium=3.141.0
  - phantomjs=2.1.1
